BG_VIDEO_PATH: "background.mp4"
BROWSER_EXECUTABLE_PATH: ""
CLEAN_TEMP: false # Not advised when rendering many at once since it's just deleting everything from tmp
CUSTOM_CONTENT_PATH: ""
CUSTOM_TITLE: ""
RESULTS_FOLDER: "results"
PREVIEW_PATH: "previews/preview.html" # To a file from which preview will be generated, you shouldn't change it
SPEED_FACTOR: 1.1
TARGET_FPS: 60
TEDDIT_ENDPOINT: "https://teddit.zaggy.nl/r/confession/comments/dju74z/i_run_a_fake_restaurant_on_a_delivery_app?api"
TEMP_FOLDER: "tmp" #
TIKTOK_VOICE: "en_us_006" #
  
# Some font settings
FONT_PATH: "fonts/ProtestStrike-Regular.ttf"
FONT_SIZE: 34
FONT_COLOR: "#FFFF00"
STROKE_COLOR: "black"
STROKE_WIDTH: 2

# For parts division
DIVIDE_INTO_PARTS: false
MAX_VIDEO_LENGTH: 60 # In seconds
FADEOUT_DURATION: 3
FADEOUT_TEXT_DURATION: 1.5
FADEOUT_FONT_PATH: "fonts/ProtestStrike-Regular.ttf"
FADEOUT_FONT_SIZE: 96
FADEOUT_FONT_COLOR: "red"