BG_VIDEO_PATH: "background.mp4"
CLEAN_TEMP: true
CUSTOM_CONTENT_PATH: "" # If specified, used instead of API post content
CUSTOM_TITLE: "" # If specified, used instead of API title
OUTPUT_FOLDER: "" # If not specified, output will be in the main directory as a title
PREVIEW_PATH: "previews/preview.html" # To a file from which preview will be generated, you shouldn't change it
TARGET_FPS: 60
TEDDIT_ENDPOINT: "" # API endpoint from which to gather information
TEMP_PATH: "tmp" # For files to be saved during the proccess
TIKTOK_VOICE: "en_us_006" # Choose one you want: https://github.com/Steve0929/tiktok-tts?tab=readme-ov-file#speaker-codes
  
# Some font settings
FONT_PATH: "fonts/Roboto.ttf"
FONT_SIZE: 36
COLOR: "#FFFF00"
STROKE_COLOR: "black"
STROKE_WIDTH: 2