BG_VIDEO_PATH: "background.mp4"
CLEAN_TEMP: false # Not advised when rendering many at once since it's just deleting everything from tmp (for now)
CUSTOM_CONTENT_PATH: "" # If specified, used instead of API post content
CUSTOM_TITLE: "" # If specified, used instead of API title
OUTPUT_FOLDER: "results" # If not specified, output will be in the main directory as a title
PREVIEW_PATH: "previews/preview.html" # To a file from which preview will be generated, you shouldn't change it
SPEED_FACTOR: 1.1
TARGET_FPS: 60
TEDDIT_ENDPOINT: "https://teddit.zaggy.nl/r/confessions/comments/1aqocr1/i_dumped_my_girlfriend_over_text_this_morning/?api" # API endpoint from which to gather information
TEMP_PATH: "tmp" # For files to be saved during the proccess
TIKTOK_VOICE: "en_us_006" # Choose one you want: https://github.com/Steve0929/tiktok-tts?tab=readme-ov-file#speaker-codes
  
# Some font settings
FONT_PATH: "fonts/ProtestStrike-Regular.ttf"
FONT_SIZE: 34
FONT_COLOR: "#FFFF00"
STROKE_COLOR: "black"
STROKE_WIDTH: 2

# For parts division
DIVIDE_INTO_PARTS: true
MAX_VIDEO_LENGTH: 60 # In seconds
FADEOUT_DURATION: 3
FADEOUT_TEXT_DURATION: 1.5
FADEOUT_FONT_PATH: "fonts/ProtestStrike-Regular.ttf"
FADEOUT_FONT_SIZE: 96
FADEOUT_FONT_COLOR: "red"